import type { Metadata } from "next";
import { Header } from "@/Components/Header";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <Header />
      <html lang="ja">
        <body>{children}</body>
      </html>
    </div>
  );
}
