import type { Metadata } from "next";
import Link from "next/link";
import { Providers } from "@/app/providers";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="ja">
        <body>
          <Providers>
            <header className="flex gap-4 p-4 bg-gray-800">
              <Link href="/" className="text-white hover:text-gray-300">
                Blog
              </Link>
              <Link href="/contact" className="text-white hover:text-gray-300">
                お問い合わせ
              </Link>
            </header>
            {children}
          </Providers>
        </body>
      </html>
    </>
  );
}
